# This travis build simply tests to see if the ndmg pipeline runs to completion.
# Note that this does not mean the ndmg pipeline is *correct* -- just that it ran to completion!
# TODO : run ndmg with `pytest`, rather than travis.
# TODO : travis breaks if you make edits directly from github, because the branch name is wrong.

# dist: xenial
# virtualenv:
#   system_site_packages: true

language: python

python:
  - "3.6"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - secure: "HBtkYB1c2euZV0PYlmCY/4RUhJmjuUa0qQTalx+liaGmPZaBNkxZ5NbBl4dXqcJ8EaoqkqtmQZUG9SMhu6zIeN8lIcRDpjeremGo5bHmnv57TJQtZGMWcpJ5Xx1AJhiQGz4GWsflKQ2uNrtv1JzwxD0RT4Ej/Hx5+0LoIBwciZPbX6OkLpX8l+cBndO9PP6fTUx4gD6NUhFzB50EP9URcilEUP5QZVngxRW3b2nhMp+G4/7SVWL13Mcsklr/DT/4jr1avlLZL/8dNHOTgHVnu8NTjpePcT40MbSpzC7UUkC3j7icn8w6JsoErDhn2knzuypvncNUoR9/opIR4/ZKr44hBV72vxjiy8lLYtV3d6O4QbgDvJbuKIXnclrPVVPiKd0rEnpeaBfnZW7+93AxEgZKCVBVlLLVclFS45r0rTa0AMRqPfcUOSk0AYWKeCyoUDLkxOoCSJP46CgE8+7R2ug86/8chjbsDzTeSDfLDE8u5SPA+F3K5rPfAfDnSJ0gFjSrUTUMRkxk11bq5ZgmCOToc3kxGYqT1yJLLAN6gO/sEeoCuqEaRxACPUQkadOf+Q1bGfzRl6uR8VZfFU1FqSEqaeK+IgLnAzIpQsGCmyymn1umkDUgd1pUmMlDD1BZ1hemfI5bvteVIzP7HKLLXC/jvbJtGV/gQa7RGvZVUK8="
    - secure: "cB63gi/NaS9XZqMhibmiRU7NAWNUyl7xwiH1NmIQkctyULO/Mk4Mc/5QS+ObPDIO6Bpfmd+RXjP/fZpbAHBWfxCUubCDxtLbkVmvO1RkgdJgL5ANfdoMc8/Q3ZmLS8KKt1t6FBGY+kNlCTdZyYVbbfMe85QYgZkJXQjghWmo5cZm9ZBIXuEqcsiOgbNBklI3fFLhjP2lGggxixswx37lHmg7gbiyJIFIBzA9+86+73Q0KlrRntAo/0uW+S9KG1+24E32vmp8nocugNIrxQbCnLMrlCPRW65QD+IGPhQRShS7oW3Ket0UT2jm7lxJMJ3q0gvr5EmEXto+vReM94/D4z5qYIo17RmqnYDUs9C3PvUQzerNQBGjZrs4xYOSkBazoUUDRMgaXI/d6YLOjAtQIDTiYsMh1p5xbUQSDD08/+71+21HWdJMfQtLAXpN2TolndiC6xox06SfGjAhWr9zsKnyS/ItyHvb8I3YN7X88HTJLYuAe40WefrI6wryB6yYIPL0H7aHhFKSUBiVYKCihPXzKxCyg8BA09k8hM8shFNT1lWP78Lj7pEB7kDAWG/EFZ7MGktk0QHagslGd1cpTNZN6NNeLI9VHTPk1sHYbaqLmg2LpeAXYUmh7E6KxkUSK5szXNZ+NVmO0IMCibbI7KZxfkhsymsMW4mypKarOz4="
  matrix:
    - SP=native MOD=det
    - SP=native_dsn MOD=det
    - SP=native MOD=prob

before_install:
  # make local input and output directories to attach to container
  - cd ..
  - mkdir -m 777 input output

  # useful log checks
  - readlink -f input
  - ls
  - pwd
  - uname -a
  - df -h
  - docker version

  # grab ndmg's travis docker image, run it with local branch attached as a volume
  - docker pull neurodata/ndmg_travis:latest
  - docker images
  - cd ndmg
  - docker run -t -d --name travis -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/ndmg -v $(readlink -f ../output):/output --entrypoint /bin/bash neurodata/ndmg_travis:latest
  - docker ps

install:
  # useful log checks for packages whose versions have given us trouble
  - docker exec -w /ndmg travis pip show dipy networkx

  # get travis branch installed
  - docker exec -w /ndmg travis pip install pytest
  - docker exec -w /ndmg travis pip install .

script:
  # Run ndmg in docker, run pytest in docker.
  # top command is to prevent travis from breaking at eddy_correct
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - docker exec travis aws s3 sync /input s3://ndmg-data/Travis-Output/
  - docker exec -w /ndmg travis ndmg --sp $SP --mod $MOD --participant_label 0025864 --session_label 1 --parcellation desikan --seeds 1 /input /output
  - kill %1
  - docker exec -w /ndmg travis pytest -v --disable-warnings
  # generate an identifier for this travis branch run using date_SP_MOD_commit_ID
  - rand=$(date +'%m-%d-%Y'-$SP-$MOD-${TRAVIS_COMMIT:0:7})
  # get name of heatmap and connectome files
  - heat=$(docker exec travis ls /output/sub-0025864/ses-1/qa/graphs_plotting)
  - csv=$(docker exec travis ls /output/sub-0025864/ses-1/dwi/roi-connectomes/desikan_space-MNI152NLin6_res-2x2x2)
  # run a command inside of docker to push heatmap and connectome to the ndmg-data s3 bucket
  - docker exec travis aws s3 sync /output/sub-0025864/ses-1/qa/graphs_plotting s3://ndmg-data/Travis-Output/$TRAVIS_BRANCH/$rand
  - docker exec travis aws s3 sync /output/sub-0025864/ses-1/dwi/roi-connectomes/desikan_space-MNI152NLin6_res-2x2x2 s3://ndmg-data/Travis-Output/$TRAVIS_BRANCH/$rand
  # print the url location for the two files on the s3 bucket
  - echo -en "\n\n\n\n\n\nHEATMAP_LOCATION = s3.console.aws.amazon.com/s3/object/ndmg-data/Travis-Output/$TRAVIS_BRANCH/$rand/$heat?region=us-east-1&tab=overview\n\nCSV_LOCATION = s3.console.aws.amazon.com/s3/object/ndmg-data/Travis-Output/$TRAVIS_BRANCH/$rand/$csv?region=us-east-1&tab=overview\n\n\n\n\n\n"
